Repository jinho7/UMC_SmuPool_GroupD_BE, pull requests merged in 2024-05, with the labels that each got.

#3 ✨ feat : Issue & PR 템플릿 완성 (#1)
  README.md
  img.png
Labels: 📃 Docs

#7 📝 Docs : README.md 수정 (#1)
  README.md
Labels: 📃 Docs

#9 ✨ [FEAT] : 기본 엔티티 및 스웨거 설정 (#6)
  README.md
  src/main/java/com/umc/smupool/SmupoolApplication.java
  src/main/java/com/umc/smupool/global/common/BaseEntity.java
  src/main/java/com/umc/smupool/global/config/SwaggerConfig.java
Labels: ✨ Feature

#10 ✨ [FEAT] 응답 통일 & Error Handler (#5)
  README.md
  build.gradle
  src/main/java/com/umc/smupool/domain/chat/controller/ChatController.java
  src/main/java/com/umc/smupool/domain/chat/exception/ChatErrorCode.java
  src/main/java/com/umc/smupool/domain/chat/exception/ChatException.java
  src/main/java/com/umc/smupool/global/apiPayload/ApiResponse.java
  src/main/java/com/umc/smupool/global/apiPayload/code/GeneralErrorCode.java
  src/main/java/com/umc/smupool/global/apiPayload/code/status/BaseErrorCode.java
  src/main/java/com/umc/smupool/global/apiPayload/exception/GeneralException.java
  src/main/java/com/umc/smupool/global/apiPayload/exception/handler/GlobalExceptionHandler.java
Labels: ✨ Feature, 🚀 chore

#12 ✨ [FEAT] WebMvcConfig & CorsConfig (#11)
  src/main/java/com/umc/smupool/global/config/CorsConfig.java
  src/main/java/com/umc/smupool/global/config/WebMvcConfig.java
Labels: ✨ Feature

#14 🌏 [CI/CD] git action 테스트 (#13)
  .github/workflows/dev_deploy.yml
Labels: 🌏 CI/CD

#15 🌏 [CI/CD] CI/CD 파이프라인 구축 (#13)
  .ebextensions_dev/00-makeFiles.config
  .ebextensions_dev/01-set-timezone.config
  .github/workflows/dev_deploy.yml
  .platform/nginx.conf
  Procfile
  build.gradle
  src/main/java/com/umc/smupool/domain/health/controller/RootController.java
Labels: ✨ Feature, 🌏 CI/CD

#16 🌏 ci: CI/CD 파이프라인 구축 재시도 (#13)
  src/main/java/com/umc/smupool/domain/health/controller/RootController.java
Labels: ✨ Feature, 🌏 CI/CD

#17 🌏 ci: CI/CD 파이프라인 구축 재시도2 (#13)
  .github/workflows/dev_deploy.yml
Labels: 🌏 CI/CD

#18 🌏 [CI/CD] CI/CD 파이프라인 구축 재시도3 (#13)
  .github/workflows/dev_deploy.yml
Labels: 🌏 CI/CD

#19 🌏 [CI/CD] CI/CD 파이프라인 구축 재시도3 (#14)
  .github/workflows/dev_deploy.yml
Labels: 🌏 CI/CD

#21 🌏 [CI/CD] CI/CD 베포 테스트 (#13)
  .github/workflows/dev_deploy.yml
Labels: 🌏 CI/CD

#22 🌏 [CI/CD] CI/CD 베포 테스트 2 (#13)
  .github/workflows/dev_deploy.yml
Labels: 🌏 CI/CD
