Repository jinho7/UMC_SmuPool_GroupD_BE, pull requests merged in 2024-06, with the labels that each got.

#27 :sparkles: feat: 매칭, 카풀존 엔티티 작성(#26)
  src/main/java/com/umc/smupool/domain/map/entity/CarpoolZone.java
  src/main/java/com/umc/smupool/domain/map/entity/Matching.java
  src/main/java/com/umc/smupool/domain/map/entity/enums/Status.java
  src/main/java/com/umc/smupool/domain/member/entity/Member.java
Labels: ✨ Feature

#30 ✨ feat: Spring Security 필터 체인 설정(#28)
  build.gradle
  src/main/java/com/umc/smupool/SmupoolApplication.java
  src/main/java/com/umc/smupool/domain/member/controller/MemberController.java
  src/main/java/com/umc/smupool/domain/member/converter/MemberConverter.java
  src/main/java/com/umc/smupool/domain/member/dto/MemberRequestDTO.java
  src/main/java/com/umc/smupool/domain/member/dto/MemberResponseDTO.java
  src/main/java/com/umc/smupool/domain/member/repository/MemberRepository.java
  src/main/java/com/umc/smupool/domain/member/service/MemberService.java
  src/main/java/com/umc/smupool/domain/member/service/impl/MemberServiceImpl.java
  src/main/java/com/umc/smupool/global/config/PrincipalDetails.java
  src/main/java/com/umc/smupool/global/config/PrincipalDetailsService.java
  src/main/java/com/umc/smupool/global/config/SecurityConfig.java
  src/main/resources/applicaiton.yml
Labels: ✨ Feature

#32 ✨ feat: Spring Security 필터 체인 설정(#28)
  build.gradle
  src/main/java/com/umc/smupool/SmupoolApplication.java
  src/main/java/com/umc/smupool/domain/member/controller/MemberController.java
  src/main/java/com/umc/smupool/domain/member/converter/MemberConverter.java
  src/main/java/com/umc/smupool/domain/member/dto/MemberRequestDTO.java
  src/main/java/com/umc/smupool/domain/member/dto/MemberResponseDTO.java
  src/main/java/com/umc/smupool/domain/member/repository/MemberRepository.java
  src/main/java/com/umc/smupool/domain/member/service/MemberService.java
  src/main/java/com/umc/smupool/domain/member/service/impl/MemberServiceImpl.java
  src/main/java/com/umc/smupool/global/config/PrincipalDetails.java
  src/main/java/com/umc/smupool/global/config/PrincipalDetailsService.java
  src/main/java/com/umc/smupool/global/config/SecurityConfig.java
  src/main/resources/applicaiton.yml
Labels: ✨ Feature

#35 🌏 [CI] ci/cd 파이프라인 구축 (#34)
  .ebextensions_dev/00-makeFiles.config
  .ebextensions_dev/01-set-timezone.config
  .github/workflows/dev_deploy.yml
  .platform/nginx.conf
  Procfile
  scripts/start.sh
  scripts/stop.sh
  src/main/java/com/umc/smupool/domain/health/controller/RootController.java
  src/main/java/com/umc/smupool/domain/member/entity/Member.java
Labels: 🌏 CI/CD

#36 🌏 [CI] ci/cd 파이프라인 구축 (#34)
  .github/workflows/main.yml
  .gitignore
  appspec.yml
  gradlew
  gradlew.bat
Labels: 🌏 CI/CD

#37 ✨ [FEAT] JWT 로그인 구현
  build.gradle
  src/main/java/com/umc/smupool/domain/member/dto/LoginRequestDTO.java
  src/main/java/com/umc/smupool/domain/member/entity/Member.java
  src/main/java/com/umc/smupool/domain/member/exception/AuthErrorCode.java
  src/main/java/com/umc/smupool/domain/member/exception/handler/AuthHandler.java
  src/main/java/com/umc/smupool/domain/member/service/impl/MemberServiceImpl.java
  src/main/java/com/umc/smupool/global/config/Security/PrincipalDetails.java
  src/main/java/com/umc/smupool/global/config/Security/PrincipalDetailsService.java
  src/main/java/com/umc/smupool/global/config/Security/SecurityConfig.java
  src/main/java/com/umc/smupool/global/config/Security/filter/LoginFilter.java
  src/main/java/com/umc/smupool/global/config/Security/jwt/JWTExceptionFilter.java
  src/main/java/com/umc/smupool/global/config/Security/jwt/JWTFilter.java
  src/main/java/com/umc/smupool/global/config/Security/jwt/JWTUtil.java
  src/main/java/com/umc/smupool/global/config/Security/jwt/JwtAccessDeniedHandler.java
  src/main/java/com/umc/smupool/global/config/Security/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/com/umc/smupool/global/config/SecurityConfig.java
Labels: ✨ Feature

#38 카플존, 매칭 CRUD(#29)
  src/main/java/com/umc/smupool/domain/map/controller/CarpoolZoneController.java
  src/main/java/com/umc/smupool/domain/map/converter/CarpoolZoneConverter.java
  src/main/java/com/umc/smupool/domain/map/dto/request/CarpoolZoneRequestDTO.java
  src/main/java/com/umc/smupool/domain/map/dto/response/CarpoolZoneResponseDTO.java
  src/main/java/com/umc/smupool/domain/map/entity/CarpoolZone.java
  src/main/java/com/umc/smupool/domain/map/entity/Matching.java
  src/main/java/com/umc/smupool/domain/map/exception/CarpoolZoneErrorCode.java
  src/main/java/com/umc/smupool/domain/map/exception/handler/CarpoolZoneHandler.java
  src/main/java/com/umc/smupool/domain/map/repository/CarpoolZoneRepository.java
  src/main/java/com/umc/smupool/domain/map/service/commandService/CarpoolZoneCommandService.java
  src/main/java/com/umc/smupool/domain/map/service/commandService/Impl/CarpoolZoneCommandServiceImpl.java
  src/main/java/com/umc/smupool/domain/map/service/queryService/CarpoolZoneQueryService.java
  src/main/java/com/umc/smupool/domain/map/service/queryService/Impl/CarpoolZoneQueryServiceImpl.java
  src/main/java/com/umc/smupool/domain/member/entity/Member.java
Labels: ✨ Feature

#40 ✨ [FEAT] @AuthMember 어노테이션 (#39)
  src/main/java/com/umc/smupool/SmupoolApplication.java
  src/main/java/com/umc/smupool/domain/map/entity/Matching.java
  src/main/java/com/umc/smupool/domain/member/controller/MemberController.java
  src/main/java/com/umc/smupool/domain/member/entity/Member.java
  src/main/java/com/umc/smupool/domain/member/service/MemberService.java
  src/main/java/com/umc/smupool/domain/member/service/impl/MemberServiceImpl.java
  src/main/java/com/umc/smupool/global/Security/exception/JWTExceptionFilter.java
  src/main/java/com/umc/smupool/global/Security/exception/JwtAccessDeniedHandler.java
  src/main/java/com/umc/smupool/global/Security/exception/JwtAuthenticationEntryPoint.java
  src/main/java/com/umc/smupool/global/Security/filter/JWTFilter.java
  src/main/java/com/umc/smupool/global/Security/filter/LoginFilter.java
  src/main/java/com/umc/smupool/global/Security/userdetails/PrincipalDetails.java
  src/main/java/com/umc/smupool/global/Security/userdetails/PrincipalDetailsService.java
  src/main/java/com/umc/smupool/global/Security/util/JWTUtil.java
  src/main/java/com/umc/smupool/global/annotation/AuthMember.java
  src/main/java/com/umc/smupool/global/annotation/AuthMemberArgumentResolver.java
  src/main/java/com/umc/smupool/global/config/SecurityConfig.java
  src/main/java/com/umc/smupool/global/config/WebMvcConfig.java
Labels: ✨ Feature

#43 :bug: fix: MemberController @AuthMember 적용 (#42)
  src/main/java/com/umc/smupool/domain/member/controller/MemberController.java
  src/main/java/com/umc/smupool/domain/member/service/MemberService.java
  src/main/java/com/umc/smupool/domain/member/service/impl/MemberServiceImpl.java
Labels: 🐞 Fix

#47 :sparkles: feat: 매칭 crud(#46)
  src/main/java/com/umc/smupool/domain/map/controller/MatchingController.java
  src/main/java/com/umc/smupool/domain/map/converter/MatchingConverter.java
  src/main/java/com/umc/smupool/domain/map/dto/request/MatchingRequestDTO.java
  src/main/java/com/umc/smupool/domain/map/dto/response/MatchingResponseDTO.java
  src/main/java/com/umc/smupool/domain/map/exception/MatchingErrorCode.java
  src/main/java/com/umc/smupool/domain/map/exception/handler/MatchingHandler.java
  src/main/java/com/umc/smupool/domain/map/repository/MatchingRepository.java
  src/main/java/com/umc/smupool/domain/map/service/commandService/Impl/MatchingCommandServiceImpl.java
  src/main/java/com/umc/smupool/domain/map/service/commandService/MatchingCommandService.java
  src/main/java/com/umc/smupool/domain/map/service/queryService/Impl/MatchingQueryServiceImpl.java
  src/main/java/com/umc/smupool/domain/map/service/queryService/MatchingQueryService.java
Labels: ✨ Feature

#48 🐛 [FIX] Matching @AuthMember 적용
  src/main/java/com/umc/smupool/domain/map/controller/MatchingController.java
  src/main/java/com/umc/smupool/domain/map/dto/request/MatchingRequestDTO.java
  src/main/java/com/umc/smupool/domain/map/service/commandService/Impl/CarpoolZoneCommandServiceImpl.java
  src/main/java/com/umc/smupool/domain/map/service/commandService/Impl/MatchingCommandServiceImpl.java
  src/main/java/com/umc/smupool/domain/map/service/commandService/MatchingCommandService.java
Labels: 🐞 Fix

#50 :sparkles: feat: 샘물 인증 구현 (#44)
  build.gradle
  src/main/java/com/umc/smupool/domain/member/controller/MemberController.java
  src/main/java/com/umc/smupool/domain/member/converter/MemberConverter.java
  src/main/java/com/umc/smupool/domain/member/dto/MemberRequestDTO.java
  src/main/java/com/umc/smupool/domain/member/entity/Member.java
  src/main/java/com/umc/smupool/domain/member/exception/AuthErrorCode.java
  src/main/java/com/umc/smupool/domain/member/service/MemberService.java
  src/main/java/com/umc/smupool/domain/member/service/impl/MemberServiceImpl.java
  src/main/java/com/umc/smupool/global/config/SecurityConfig.java
Labels: ✨ Feature

#51 :sparkles: [FEAT] 샘물 인증 구현 (#44)
  src/main/java/com/umc/smupool/domain/auth/controller/AuthController.java
  src/main/java/com/umc/smupool/domain/auth/dto/AuthRequestDTO.java
  src/main/java/com/umc/smupool/domain/auth/dto/AuthResponseDTO.java
  src/main/java/com/umc/smupool/domain/auth/service/AuthService.java
  src/main/java/com/umc/smupool/domain/member/dto/AuthMemberRequestDTO.java
Labels: ✨ Feature

#53 ✨ [FEAT] 매칭 API 구현 (#49)
  src/main/java/com/umc/smupool/domain/map/converter/MatchingConverter.java
  src/main/java/com/umc/smupool/domain/map/dto/response/MatchingResponseDTO.java
  src/main/java/com/umc/smupool/domain/map/entity/Matching.java
  src/main/java/com/umc/smupool/domain/map/service/commandService/Impl/MatchingCommandServiceImpl.java
  src/main/java/com/umc/smupool/domain/map/service/queryService/Impl/MatchingQueryServiceImpl.java
Labels: ✨ Feature

#54 [FEAT] :sparkles: feat: 매칭 API
  src/main/java/com/umc/smupool/domain/map/controller/MatchingController.java
  src/main/java/com/umc/smupool/domain/map/dto/request/MatchingRequestDTO.java
  src/main/java/com/umc/smupool/domain/map/event/MatchingCompletedEvent.java
  src/main/java/com/umc/smupool/domain/map/service/commandService/Impl/MatchingCommandServiceImpl.java
  src/main/java/com/umc/smupool/domain/map/service/commandService/MatchingCommandService.java
Labels: ✨ Feature

#55 [FEAT] :sparkles: feat: 알림 기능
  src/main/java/com/umc/smupool/domain/alarm/controller/ChatController.java
  src/main/java/com/umc/smupool/domain/alarm/dto/MatchingAlarmDTO.java
  src/main/java/com/umc/smupool/domain/alarm/dto/MessageAlarmDTO.java
  src/main/java/com/umc/smupool/domain/alarm/event/MatchingEvent.java
  src/main/java/com/umc/smupool/domain/alarm/service/AlarmService.java
  src/main/java/com/umc/smupool/domain/alarm/service/impl/AlarmServiceImpl.java
  src/main/java/com/umc/smupool/global/config/WebSocketConfig.java
Labels: ✨ Feature

#58 :bug: [FIX] 멤버 회원 가입 수정 (#56)
  src/main/java/com/umc/smupool/domain/auth/controller/AuthController.java
  src/main/java/com/umc/smupool/domain/auth/service/AuthService.java
  src/main/java/com/umc/smupool/domain/member/controller/MemberController.java
  src/main/java/com/umc/smupool/domain/member/converter/MemberConverter.java
  src/main/java/com/umc/smupool/domain/member/service/MemberService.java
  src/main/java/com/umc/smupool/domain/member/service/impl/MemberServiceImpl.java
Labels: 🐞 Fix

#59 :recycle: [REFACTOR] 매칭, 알림 API 개선
  build.gradle
  src/main/java/com/umc/smupool/domain/alarm/controller/ChatAlarmController.java
  src/main/java/com/umc/smupool/domain/alarm/controller/scheduler/MatchingScheduler.java
  src/main/java/com/umc/smupool/domain/alarm/dto/MessageAlarmDTO.java
  src/main/java/com/umc/smupool/domain/alarm/service/impl/AlarmServiceImpl.java
  src/main/java/com/umc/smupool/domain/map/controller/MatchingAlarmController.java
  src/main/java/com/umc/smupool/domain/map/controller/MatchingController.java
  src/main/java/com/umc/smupool/domain/map/converter/MatchingConverter.java
  src/main/java/com/umc/smupool/domain/map/dto/request/MatchingRequestDTO.java
  src/main/java/com/umc/smupool/domain/map/entity/Matching.java
  src/main/java/com/umc/smupool/domain/map/service/commandService/Impl/MatchingCommandServiceImpl.java
  src/main/java/com/umc/smupool/domain/map/service/commandService/MatchingCommandService.java
  src/main/java/com/umc/smupool/global/config/SecurityConfig.java
  src/main/java/com/umc/smupool/global/config/WebSocketConfig.java
Labels: ♻️ Refactor, ✨ Feature

#61 :recycle: refactor: 매칭 서비스 수정
  src/main/java/com/umc/smupool/domain/map/exception/MatchingErrorCode.java
  src/main/java/com/umc/smupool/domain/map/service/commandService/Impl/MatchingCommandServiceImpl.java
Labels: ♻️ Refactor
